### PR TITLE
Fixes messed up header view after notifyDataSetChanged() from listadapter

### PR DESCRIPTION
**Pull request by mozarcik**
After notifyDataSetChanged() from LIstAdapter container view is triggered to relayout all children including header view. During relayout it does not keep offset but sets top position based on gravity to 0. After relayout Helper class is notified about new scroll and listview top visible position is not changed so we can just check for that. If header view top position is 0 but previous top position was <0 and listview first visible position haven't changed we can set header offset to last top position.

### CODE REVIEW

**Comment by rv-vdev** [comment]
Can a similar thing be done for mScrollView . Dynamic resizing of scrollview also leads to a similar wrong offset of mHeaderView

**Comment by mozarcik** [comment]
I think something like this should fix also issue with ScrollView. Because after resizing any view there is probably relayout on parent view which causes placing mHeaderView at top (it ignores previous settings for offset) and it just need reverting this offset. This could be also done by creating custom view for mHeaderView.

**Comment by ManuelPeinado** [comment]
Hi mozarcik , thanks a lot for helping out.

I don't think that your pull request is a real solution to the problem, though. Please checkout the "dev" branch in this repo and run the "Dataset Change" example. It failed before I applied your changes, and it still fails.

**Comment by mozarcik** [comment]
Hi Manuel, 

I'll check it out. If it doesn't work in every situation then i think there is one good solution to this. 

I think that there should be a custom view extending FrameLayout for container of header and listview/scrollview, then  on relayout it should check top position of header view and restore it after relayout (i don't know if that'll work as i described, maybe it should take care of placing header view at all). 

I'll try to create such a view and let you know if it works.

**Comment by mozarcik** [comment]
Hello Manuel,

I've looked into that sample and it actually worked with header view but listViewBackground was still messed up.
I've created RootLayout which takes care of restoring top position of headerview and listviewbackground.

It works with changing listview and scrollview now. Here's updated sample: http://motyczko.pl/fadingab_sample.apk

**Pull request merged**
